package com.example.guessthenumberwebguigame.view;

import org.springframework.stereotype.Component;

@Component("guessNumberModelMessagesGenerator")
public class GuessNumberGameMessagesGenerator {
    private static final String WELCOME_MESSAGE = "WELCOME TO THE *GUESS NUMBER* GAME!!!";
    private static final String GAME_RULES_MESSAGE = "The aim of the game is to guess a number from customizable " +
            "range\n randomly generated by a computer. After each number guessing attempt you will be informed if your" +
            " number greater, less or equal to the actual generated number.\n If your number is equal to the actual " +
            "number than you have won.\n Try to use as few attempts as you can. Good luck!";

    private static final String NOT_INTEGER_INPUT_MESSAGE = "The input can't be parsed to integer(s).\n" +
            " Can you reenter the correct integer number input please?";
    private static final String UPPER_AND_LOWER_BOUNDS_INCORRECT_MESSAGE = "Incorrect number bounds values. Upper bound " +
            "should be greater than the lower bound.\nTry to enter number bounds values again please.";

    private static final String NUMBER_ISNT_IN_CORRECT_RANGE_MESSAGE = "The number is not inside correct range: from %s " +
            "to %s. Please try to enter the number again.";

    private static final String GUESSED_NUMBER_ALREADY_TRIED_MESSAGE = "You've already tried with number %s. Please try " +
            "another number.";

    private static final String YOUR_NUMBER_GREATER_MESSAGE = "GREATER THAN GENERATED NUMBER.";

    private static final String YOUR_NUMBER_LESS_MESSAGE = "LESS THAN GENERATED NUMBER.";

    private static final String YOUR_NUMBER_GUESSED_CORRECT_MESSAGE = "You've guessed the correct number!";

    private static final String TOTAL_ATTEMPTS_USED_MESSAGE = "You've used %s attempts.";

    private String generateMessage(String message, String... args) {
        return String.format(message, args);
    }

    public String generateNotIntegerInputMessage() {
        return generateMessage(NOT_INTEGER_INPUT_MESSAGE);
    }

    public String generateNumberIsntInCorrectRangeMessage(int lowerBound, int upperBound) {
        return generateMessage(NUMBER_ISNT_IN_CORRECT_RANGE_MESSAGE, String.valueOf(lowerBound), String.valueOf(upperBound));
    }

    public String generateGuessedNumberAlreadyTriedMessage(int guessedNumber) {
        return generateMessage(GUESSED_NUMBER_ALREADY_TRIED_MESSAGE, String.valueOf(guessedNumber));
    }

    public String generateYourNumberGreaterMessage() {
        return generateMessage(YOUR_NUMBER_GREATER_MESSAGE);
    }

    public String generateYourNumberLessMessage() {
        return generateMessage(YOUR_NUMBER_LESS_MESSAGE);
    }

    public String generateYourNumberGuessedCorrectMessage(int totalAttemptsUsed) {
        return generateMessage(YOUR_NUMBER_GUESSED_CORRECT_MESSAGE) + "\n" +
                generateMessage(TOTAL_ATTEMPTS_USED_MESSAGE, String.valueOf(totalAttemptsUsed));
    }


    public String generateUpperAndLowerBoundsIncorrectMessage() {
        return generateMessage(UPPER_AND_LOWER_BOUNDS_INCORRECT_MESSAGE);
    }
}
